### ISSUE TITLE
So cool!

### ISSUE THREAD

**Issue by RobLoach** [taniarascia/chip8#10]
This is so cool! Found chip8 through the dependency list on [npm.im/raylib](https://www.npmjs.com/package/raylib). Just a note that I've updated it to raylib 3.5.0. Tested out the update in chip8, and it still works well.

Awesome work! :rocket:

**Comment by taniarascia** [comment]
@RobLoach Hey, awesome, thanks! I'm glad you enjoyed it! Thank you for making it possible.

**Comment by RobLoach** [comment]
:+1: :wink:
