### ISSUE TITLE
Bad command ADD(Vx, Vy).

### ISSUE THREAD

**Issue by xiaoyu2006** [taniarascia/chip8#8]
Command `ADD(Vx, Vy)` is described like this:

> # 8xy4 - ADD Vx, Vy
> Set Vx = Vx + Vy, set VF = carry.
> The values of Vx and Vy are added together. If the result is greater than 8 bits (i.e., > 255,) VF is set to 1, otherwise 0. Only the lowest 8 bits of the result are kept, and stored in Vx.

But at
https://github.com/taniarascia/chip8/blob/cc9dd63f27a116ce71f663b13fd911e826f5e21d/classes/CPU.js#L249
`this.registers[args[0]]` is already modified at the previous line
https://github.com/taniarascia/chip8/blob/cc9dd63f27a116ce71f663b13fd911e826f5e21d/classes/CPU.js#L248
and also has lost it's higher bits.

I think Line#249 should be moved before Line#248.

--------------------

Am I misunderstanding something?

**Comment by taniarascia** [comment]
That's a good point! Looks like a bug.

**Comment by xiaoyu2006** [comment]
Pull request submitted. @taniarascia plz review & merge!
:-)
